"""add_chat_memory_table

Revision ID: 0d3c8e44a45d
Revises: 0ae705bab31d
Create Date: 2025-02-12 17:12:59.952470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d3c8e44a45d'
down_revision = '0ae705bab31d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.alter_column('chatroom', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chatroom', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chatroom', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'chatroom', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('token_usage', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('token_usage', 'cache_write_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token_usage', 'cache_hit_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('token_usage', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'token_usage', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_usage', type_='foreignkey')
    op.alter_column('token_usage', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('token_usage', 'cache_hit_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('token_usage', 'cache_write_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('token_usage', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'chatroom', type_='foreignkey')
    op.alter_column('chatroom', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chatroom', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chatroom', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('project',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_instruction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='project_pkey')
    )
    # ### end Alembic commands ### 